[package]
name = "muse"
version = "0.1.0"
edition = "2021"
authors = ["Hubert Kedziora <hubert.kedziora1@proton.me>"]
description = "A SaaS for streaming music."

[dependencies]
uuid = { version = "1.11.0", features = ["v4"] }
