[package]
name = "muse"
version = "0.1.0"
edition = "2021"
authors = ["Hubert Kedziora <hubert.kedziora1@proton.me>"]
description = "A SaaS for streaming music."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
